// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcore

import (
	"database/sql"

	"github.com/google/uuid"
)

type Distributor struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type DistributorsStaff struct {
	ID             uuid.UUID
	DistributorsID uuid.UUID
	UserID         uuid.UUID
	Role           string
	CreatedAt      sql.NullTime
}
