// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcore

import (
	"database/sql"

	"github.com/google/uuid"
)

type Distributor struct {
	ID        uuid.UUID
	Name      string
	OwnerID   uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type DistributorsStaff struct {
	ID             uuid.UUID
	DistributorsID uuid.UUID
	UserID         uuid.UUID
	Role           string
	CreatedAt      sql.NullTime
}

type Place struct {
	ID            uuid.UUID
	Name          string
	Type          int32
	DistributorID uuid.UUID
	StreetID      uuid.UUID
	HouseNumber   string
	Location      interface{}
	TotalScore    int32
	ReviewsCount  int32
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
}

type PlaceType struct {
	ID   int32
	Name string
}

type PlacesStaff struct {
	ID        uuid.UUID
	PlaceID   uuid.UUID
	UserID    uuid.UUID
	Role      string
	CreatedAt sql.NullTime
}
