// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: places_types.sql

package sqlcore

import (
	"context"
)

const createPlacesType = `-- name: CreatePlacesType :one
INSERT INTO place_types (name)
VALUES ($1)
RETURNING id, name
`

func (q *Queries) CreatePlacesType(ctx context.Context, name string) (PlaceType, error) {
	row := q.db.QueryRowContext(ctx, createPlacesType, name)
	var i PlaceType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deletePlacesType = `-- name: DeletePlacesType :exec
DELETE FROM place_types
WHERE id = $1
`

func (q *Queries) DeletePlacesType(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deletePlacesType, id)
	return err
}

const getPlacesTypeByID = `-- name: GetPlacesTypeByID :one
SELECT id, name FROM place_types
WHERE id = $1
`

func (q *Queries) GetPlacesTypeByID(ctx context.Context, id int32) (PlaceType, error) {
	row := q.db.QueryRowContext(ctx, getPlacesTypeByID, id)
	var i PlaceType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getPlacesTypeByName = `-- name: GetPlacesTypeByName :one
SELECT id, name FROM place_types
WHERE name = $1
`

func (q *Queries) GetPlacesTypeByName(ctx context.Context, name string) (PlaceType, error) {
	row := q.db.QueryRowContext(ctx, getPlacesTypeByName, name)
	var i PlaceType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updatePlacesName = `-- name: UpdatePlacesName :one
UPDATE place_types
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdatePlacesNameParams struct {
	ID   int32
	Name string
}

func (q *Queries) UpdatePlacesName(ctx context.Context, arg UpdatePlacesNameParams) (PlaceType, error) {
	row := q.db.QueryRowContext(ctx, updatePlacesName, arg.ID, arg.Name)
	var i PlaceType
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
