openapi: 3.0.0
info:
  title: Test
  description: Test
  version: 0.0.1

paths:
  /users/create:
    post:
      summary: Create a new user
      operationId: createUser
      responses:
        '201':
          description: Created
components:
  schemas:
